apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: blog
  labels:
    app: blog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: 192.168.201.129/demo/blog-service:128-5c21f08
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              value: "blog_db"
            - name: DB_USER
              value: "blog"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog
spec:
  type: ClusterIP
  selector:
    app: blog-service
  ports:
    - port: 80
      targetPort: 5000
