apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: blog
  annotations:
    cert-manager.io/cluster-issuer: kalem-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - blog.murataksu.net
      secretName: blog-tls
  rules:
    - host: blog.murataksu.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
